# Generated by Django 2.2 on 2019-04-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(verbose_name='date approved')),
            ],
        ),
    ]
