# Generated by Django 2.2 on 2019-04-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='github_username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invite',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
