# Generated by Django 2.2 on 2019-04-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190410_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invite',
            name='github_username',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
