# Generated by Django 2.2 on 2019-04-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190410_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email_address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
