# Generated by Django 2.2 on 2019-04-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190417_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='slack_activated',
            field=models.BooleanField(default=False),
        ),
    ]
